name: TypeScript - Continuous Integration / Continuous Delivery

on:
  push:
    branches:
      - "master"
      - "develop"
      - "hotfix/**"
      - "feature/**"
      - "renovate/**"
      - "dependabot/**"
    paths:
      - "languages/javascript/**"

jobs:
  ci:
    name: TypeScript - CI / CD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.18.0"
      - name: Install pnpm
        run: npm install -g pnpm
        working-directory: "./languages/javascript"
      - name: Install Dependencies
        run: pnpm install
        working-directory: "./languages/javascript"
      - name: Linting
        run: pnpm run lint
        working-directory: "./languages/javascript"
      - name: Unit Test
        run: pnpm run test --concurrency 1
        working-directory: "./languages/javascript"
      - name: Build Production
        run: pnpm run build --concurrency 1
        working-directory: "./languages/javascript"
